openapi: '3.0.2'
info:
  title: Grocery Price API
  description: |
    This API converts a function into a resource by applying models to the
     resource to enable a functional API in a RESTful way.
  contact:
    name: Anthony Ikeda
    email: anthony.ikeda@thoughtworks.com
  version: '0.0.1'
servers:
  - url: http://localhost:8080/
    description: "Local"
paths:
  /calculation/v1:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
      responses:
        '201':
          description: Created
    
  /calculation/v1/{calculationId}:
    get:
      parameters:
        - in : path
          required: true
          name : calculationId
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculationResponse'
        '404':
          description: NOT FOUND
components:
  schemas:
    LineItem:
      type: object
      properties:
        productId:
          type: string
        qty:
          type: number
        totalCost:
          type: number
    TaxItem:
      type: object
      properties:
        taxType:
          type: string
        taxPercentage:
          type: number
        totalCost:
          type: number
    CalculationRequest:
      type: object
      properties:
        customerId:
          type: string
        calculationType:
          type: string
          enum:
            - TOTALS
            - TAXES
            - ALL
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
    CalculationResponse:
      type: object
      properties:
        calculationId:
          type: number
        calculations:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        taxes:
          type: array
          items:
            $ref: '#/components/schemas/TaxItem'
