name: Release to DockerHub

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: setup_java
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: temurin
        cache: maven
    - id: jib_build
      name: Build with JIB
      run: ./mvnw clean compile jib:dockerBuild
    - id: docker_login
      name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    - id: build_image
      name: Build Docker image - no tests
      run: ./mvnw clean verify -DskipTests=true jib:dockerBuild
      env:
        SPRING_PROFILES_ACTIVE: "test"
        PRODUCT_POD_NAME: localhost
    - id: docker_push
      name: Push to DockerHub
      run: docker push anthonyikeda/grocery-price-api
